service: nodejs-meetup

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: functions/hello.handler
    events:
    - http:
        path: hello
        method: get

plugins:
- serverless-offline
